### ISSUE TITLE
Error when clicking on join sign

### ISSUE THREAD

**Issue by KarlOfDuty** [Remyk1/Survival-Games#4]
**Describe the bug**
We get this error when players click the join sign. It starts happening when we have a lot of players on so it's probably from a lot of players spamming it.

**Errors**
If applicable, also add the errror getting.
![image](https://user-images.githubusercontent.com/18099825/58914664-68976900-871f-11e9-93bc-c1033e564790.png)

**Specfiy which versions your using**
 - Plugin version: 7.0.3
 - Spigot version: Paper 624
 - WorldEdit version: Fawe 1.13.135

**Comment by Remyk1** [comment]
It's probably because you don't have enough signs (the plugin needs 3) i think i will just add a if statement checking whether or not there are  3 or more signs, for people who don't want to see who is in the arena.

but as it's a small thing i will add it in the next update, so for now just add one more sign.

**Comment by KarlOfDuty** [comment]
Ah, thanks I wasn't the one who set up the wall so I didn't realise anything was missing there.
